NAME = philosophers
CC = cc 
CFLAGS = -Wall -Werror -Wextra -g3
RM = rm
RMFLAGS = -rf

SRC = 
SRC_BONUS =

OBJS = $(SRC:.c=.o)
OBJE_BONUS = $(SRC_BONUS:.c=.o)

$(NAME): all
		Make -C

clean: 
	$(RM) $(RMFLAGS) $(OBJE_BONUS)

fclean:
	$(RM) $(RMFLAGS) $(OBJE_BONUS)


.PHOHY: all bonus clean fclean re